// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXpQeFfZzdksPPjxWpEWkUhZiN_r3oHWA',
    appId: '1:938340211910:web:cd6233b88f8c77a20f4bc7',
    messagingSenderId: '938340211910',
    projectId: 'fungible-rewards',
    authDomain: 'fungible-rewards.firebaseapp.com',
    storageBucket: 'fungible-rewards.appspot.com',
    measurementId: 'G-B802HT4DTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtgBaeUYOrFjH4Em5QS4L4ijiPZfQI6KM',
    appId: '1:938340211910:android:8b64fc6ddc9984f70f4bc7',
    messagingSenderId: '938340211910',
    projectId: 'fungible-rewards',
    storageBucket: 'fungible-rewards.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAafSX55-moYYyuPCl-g-1ejU3KmZXg4',
    appId: '1:938340211910:ios:56c8e4f946047c540f4bc7',
    messagingSenderId: '938340211910',
    projectId: 'fungible-rewards',
    storageBucket: 'fungible-rewards.appspot.com',
    iosClientId: '938340211910-jn1u4qf3aipc4s2tl7ldk73eti88ljbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipgrid',
  );
}
